ports:
- port: 8002
  onOpen: open-preview
tasks:
- name: Nginx
  command: >
    sed -ri 's|root [^;]+;|root '"$GITPOD_REPO_ROOT"'/public;|g' /etc/nginx/nginx.conf &&
    while [ ! -f /tmp/terminado ] ; do sleep 1; done ; service nginx start &&
    multitail /var/log/nginx/access.log -I /var/log/nginx/error.log
- name: Terminal
  init: >
    composer install;
    touch /tmp/terminado
  command: >
    clear;
    echo "";
    echo "Cosas que puedes hacer en este terminal:";
    echo " * service nginx stop";
    echo " * service nginx start";
    echo " * gp open /var/log/nginx/access.log";
    echo " * gp open /var/log/nginx/error.log";